name: bellkat

default-extensions:
  - DerivingStrategies
  - TypeFamilies
  - GeneralizedNewtypeDeriving
  - FunctionalDependencies
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - NoPolyKinds

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-incomplete-uni-patterns
  - -fwarn-missing-deriving-strategies

dependencies:
  - base
  - containers
  - more-containers
  - diagrams-lib
  - diagrams-cairo
  - QuickCheck
  - fixed-vector
  - data-default
  - these
  - pointed
  - base-orphans
  - mtl
  - smallcheck
  - probability

library:
  source-dirs: src
  exposed-modules:
    - BellKAT.Drawing
    - BellKAT.Definitions
    - BellKAT.PolicyEmbeddings
    - BellKAT.ActionEmbeddings
    - BellKAT.Definitions.Core
    - BellKAT.Definitions.Atomic
    - BellKAT.Definitions.Structures
    - BellKAT.Definitions.Structures.Basic
    - BellKAT.Definitions.Policy
    - BellKAT.Definitions.Policy.Extra
    - BellKAT.Implementations.InterleavingOneStepHistoryQuantum
    - BellKAT.Implementations.InterleavingOneStepHistoryQuantum.FunctionStep
    - BellKAT.Implementations.InterleavingOneStepHistoryQuantum.FreeStep
    - BellKAT.Implementations.TimelyHistoryQuantum
    - BellKAT.Implementations.StepHistoryQuantum
    - BellKAT.Implementations.HistoryQuantum
    - BellKAT.Implementations.Automata
    - BellKAT.Implementations.Automata.NFA
    - BellKAT.Implementations.AutomataExecution
    - BellKAT.Implementations.AutomataStepHistoryQuantum
    - BellKAT.Implementations.AtomicOneStepHistoryQuantum
    - BellKAT.Utils.UnorderedTree
    - BellKAT.Utils.NonEmpty
    - BellKAT.Utils.Choice
    - BellKAT.Utils.PartialNDEndo
    - BellKAT.DSL
    - BellKAT.Test
    - BellKAT.Test.QuickCheck
    - BellKAT.Prelude

executables:
  p1:
    dependencies: 
      - bellkat
    main: examples/P1.hs
  p2:
    dependencies: 
      - bellkat
    main: examples/P2.hs
  p1text:
    dependencies: 
      - bellkat
    main: examples/P1Text.hs
  p2text:
    dependencies: 
      - bellkat
    main: examples/P2Text.hs
  p3:
    dependencies: 
      - hspec
      - bellkat
    main: examples/P3.hs

tests:
  spec: 
    main: Spec
    source-dirs: 
      - test/main
      - src
    dependencies: 
      - hspec
  small:
    source-dirs:
      - test/small
      - src
    dependencies: 
      - hspec
    main: SpecSmall
